# Generated by Django 3.0.3 on 2020-02-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['parent_category', 'order'], 'verbose_name_plural': 'Subcategories'},
        ),
    ]
