# Generated by Django 3.0.2 on 2020-01-29 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_per_page', models.IntegerField(default=20, verbose_name='Products Per Page')),
                ('product_link_validator', models.TextField(max_length=1000)),
                ('photos_link_validator', models.TextField(max_length=1000)),
                ('product_duplication_superuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Product Duplication Superuser')),
            ],
        ),
    ]
