# Generated by Django 3.0.2 on 2020-01-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='products_per_page',
            field=models.IntegerField(default=20, verbose_name='Products Per Page'),
        ),
    ]
