# Generated by Django 3.0.2 on 2020-01-31 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20200130_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='product_duplication_superuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_duplication_superuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='products_per_page',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('alt', models.CharField(max_length=100, verbose_name='Alternative text')),
                ('image', models.ImageField(upload_to='base/social-links/')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Configuration')),
            ],
        ),
    ]
