# Generated by Django 3.0.2 on 2020-01-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200131_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='photos_link_validator',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='product_link_validator',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
