# Generated by Django 3.0.3 on 2020-04-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200415_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileconfiguration',
            name='password',
            field=models.CharField(blank=True, help_text="Leave it blank, if you don't want to use a password protection for your products", max_length=50, null=True),
        ),
    ]
