# Generated by Django 3.0.3 on 2020-04-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200415_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileconfiguration',
            options={'permissions': [('can_interact_with_all_user_profile_configurations', 'Can interact with all user profile configurations'), ('can_interact_with_his_own_user_profile_configuration', 'Can interact with his own user profile configuration')]},
        ),
    ]
