# Generated by Django 3.0.3 on 2020-04-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200415_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileconfiguration',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
