# Generated by Django 3.0.3 on 2020-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200419_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileconfiguration',
            name='password',
            field=models.CharField(blank=True, help_text='Leave it blank or type None if you do not want to use the password protection for your products.', max_length=50, null=True),
        ),
    ]
