# Generated by Django 3.0.3 on 2020-06-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20200613_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_interact_with_all_profiles', 'Can interact with all profiles'), ('can_interact_with_his_own_profile', 'Can interact with his own profile')]},
        ),
    ]
