# Generated by Django 3.0.3 on 2020-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_configuration_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='how_to_buy',
            field=models.URLField(blank=True, help_text="Only visible on the homepage user's page"),
        ),
    ]
