# Generated by Django 3.0.7 on 2020-11-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200616_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='additional_head_code_details_page_sellers_without_home_page_user',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
