# Generated by Django 3.0.7 on 2020-11-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_configuration_additional_head_code_details_page_sellers_without_home_page_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='additional_head_code_details_page_sellers_without_home_page_user',
            new_name='additional_head_code_on_details_page_for_sellers_excluding_home_page_user',
        ),
    ]
