# Generated by Django 3.0.7 on 2020-11-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20201110_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='additional_head_code_on_details_page_for_sellers_excluding_home_page_user',
            new_name='add_head_code_det_excl_hpu',
        ),
    ]
