# Generated by Django 3.0.7 on 2020-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20201110_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='add_head_code_det_excl_hpu',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Additional head code on details page for sellers excluding home page user'),
        ),
    ]
