# Generated by Django 3.0.2 on 2020-01-10 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200110_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 22, 54, 25, 663579, tzinfo=utc), editable=False),
        ),
    ]
