# Generated by Django 3.0.2 on 2020-01-10 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 23, 12, 55, 890591, tzinfo=utc), editable=False),
        ),
    ]
