# Generated by Django 3.0.2 on 2020-01-10 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200111_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 23, 14, 22, 781351, tzinfo=utc), editable=False),
        ),
    ]
