# Generated by Django 3.0.2 on 2020-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200119_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reflink',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
