# Generated by Django 3.0.2 on 2020-01-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_modified']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='photos_link',
        ),
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(default='google', max_length=1000),
            preserve_default=False,
        ),
    ]
