# Generated by Django 3.0.2 on 2020-01-29 20:11

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200129_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(max_length=1000, validators=[products.models.product_link_validator]),
        ),
    ]
