# Generated by Django 3.0.2 on 2020-01-29 20:15

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200129_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos_link',
            field=models.URLField(max_length=1000, validators=[products.models.photos_link_validator]),
        ),
    ]
