# Generated by Django 3.0.2 on 2020-02-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200131_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='products.Category'),
            preserve_default=False,
        ),
    ]
