# Generated by Django 3.0.3 on 2020-02-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200209_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_modified']},
        ),
    ]
