# Generated by Django 3.0.3 on 2020-02-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200209_1957'),
        ('products', '0030_auto_20200209_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='categories.Subcategory'),
        ),
    ]
