# Generated by Django 3.0.3 on 2020-02-10 21:38

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200210_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos_link',
            field=models.URLField(max_length=5000, validators=[products.models.photos_link_validator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(max_length=5000, validators=[products.models.product_link_validator]),
        ),
    ]
