# Generated by Django 3.0.3 on 2020-02-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20200210_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_modified'], 'permissions': [('can_interact_with_his_own_products', 'Can interact with his own products')]},
        ),
    ]
